#!/bin/bash

dir=$PWD

while [ ! -f $dir/wiggle ]
do
  case $dir in
    / )    echo >&2 Cannot find wiggle program : $WIGGLE
       exit 1;;
    * ) dir=${dir%/*}
  esac
done
export WIGGLE=$dir/wiggle

if [ -d tests ]
then cd tests
fi

status=0
ok=0
fail=0

find . -name core | xargs rm -f
list=$(find . -type f \( -name script -o -name diff -o -name ldiff \
	-o -name rediff -o -name merge -o -name wmerge -o -name lmerge -o -name replace \) 
      )
for path in $list
do
  dir=${path%/*}
  base=${path##*/}
  (
    cd $dir
    > .time
    case $base in 
	script ) ./script ;;
	diff ) if [ -f new ]
		then /usr/bin/time -o .time -f '%U' $WIGGLE -dw orig new | diff -u diff - ; xit=$?
		else /usr/bin/time -o .time -f '%U' $WIGGLE -dwp1 orig patch | diff -u diff - ; xit=$?
		fi
		;;
	ldiff ) if [ -f new ]
		then /usr/bin/time -o .time -f '%U' $WIGGLE -dl orig new | diff -u ldiff - ; xit=$?
		else /usr/bin/time -o .time -f '%U' $WIGGLE -dlp1 orig patch | diff -u ldiff - ; xit=$?
		fi
		;;
	reldiff ) /usr/bin/time -o .time -f '%U' $WIGGLE -dl patch | diff -u reldiff - ; xit=$?
		;;
	rediff ) /usr/bin/time -o .time -f '%U' $WIGGLE -dw patch | diff -u rediff - ; xit=$?
		;;
	merge )  if [ -f patch ]
		 then /usr/bin/time -o .time -f '%U' $WIGGLE -m orig patch | diff -u merge - ; xit=$?
		 elif [ -f new ] 
                 then /usr/bin/time -o .time -f '%U' $WIGGLE -m orig new new2 | diff -u merge - ; xit=$?
		 else /usr/bin/time -o .time -f '%U' $WIGGLE -m orig | diff -u merge - ; xit=$?
		 fi
		;;
	replace ) cp orig orig.tmp
		 if [ -f patch ]
		 then /usr/bin/time -o .time -f '%U' $WIGGLE -mr orig.tmp patch 
		 else /usr/bin/time -o .time -f '%U' $WIGGLE -mr orig.tmp new new2
		 fi
		 diff -u merge orig.tmp ; xit=$?
		 rm  orig.tmp orig.tmp.porig
		;;
	lmerge )  if [ -f patch ]
		 then /usr/bin/time -o .time -f '%U' $WIGGLE -ml orig patch | diff -u lmerge - ; xit=$?
		 else /usr/bin/time -o .time -f '%U' $WIGGLE -ml orig new new2 | diff -u lmerge - ; xit=$?
		 fi
		 ;;
	wmerge )  if [ -f patch ]
		 then /usr/bin/time -o .time -f '%U' $WIGGLE -mw orig patch | diff -u wmerge - ; xit=$?
		 else /usr/bin/time -o .time -f '%U' $WIGGLE -mw orig new new2 | diff -u wmerge - ; xit=$?
		 fi
		 ;;
   esac
   if [ $xit = 0 ]; then msg=SUCCEEDED; else msg=FAILED; fi
   echo $path $msg `grep -v 'Command exited' .time 2> /dev/null`
   rm -f .time
   exit $xit
  ) 
  if [ $? = 0 ]
  then let ok++; 
  else status=1 ; let fail++ 
  fi
done
find . -name core -ls
echo $ok succeeded and $fail failed
exit $status
